#!/bin/bash
### wals1-int dpv update script

PATH=/bin:/home/amsauto/bin
LD_LIBRARY_PATH=/opt/mgicoa/lib:/usr/lib
export LD_LIBRARY_PATH
LOG=/home/amsauto/bin/updatedpv_wals1-int.log

### verify data
cd /home/amsauto/data
[ -f dpv.done ] && rm -f dpv.done || exit 1
[ -f verified.tag ] && rm -f verified.tag
echo "########################################" >> $LOG
echo "`date`:  new data found" >> $LOG
### Prepare data
gunzip *gz
tar xf dpv*tar &
tar xf fcs*tar &
wait
### Check integrity of data
md5sum -c dpv*md5 > /dev/null
X=$?
md5sum -c fcs*md5 > /dev/null
Y=$?
[ $X != 0 ] || [ $Y !=  0 ] && {
  echo "`date`:  md5sum check failed" >> $LOG
  echo "" | mailx -s "md5sum check failed on wals1-int" 9014774388@my2way.com
  exit 1
}
echo "`date`:  md5sum check passed" >> $LOG

### backup data
rm -rf /opt/mgicoa/amsdata.bak
mv -f /opt/mgicoa/amsdata /opt/mgicoa/amsdata.bak
mkdir /opt/mgicoa/amsdata
cp -p /opt/mgicoa/amsdata.bak/dpv* /opt/mgicoa/amsdata &
cp -p /opt/mgicoa/amsdata.bak/dsadrfle.* /opt/mgicoa/amsdata &
cp -p /opt/mgicoa/amsdata.bak/dszipfle.* /opt/mgicoa/amsdata &
cp -p /opt/mgicoa/amsdata.bak/libz4sun.so /opt/mgicoa/amsdata &
cp -p /opt/mgicoa/amsdata.bak/sample* /opt/mgicoa/amsdata &
cp -p /opt/mgicoa/amsdata.bak/z4* /opt/mgicoa/amsdata &
wait
echo "`date`:  data backed up.  updating . . . " >> $LOG

### update data
rm -f /home/amsauto/data/*tar
rm -f /home/amsauto/data/*md5
cp * /opt/mgicoa/amsdata
chmod 775 /opt/mgicoa/amsdata/* >/dev/null

### restart daemon and test
cd /opt/mgicoa/amsdata
./dpv2s -k 2>> $LOG
[ -f /tmp/dpv.pid ] && kill -9 `cat /tmp/dpv.pid` >/dev/null
./dpv2s >> $LOG
cd /home/amsauto/bin
./dpv_test1.e
ONE=$?
./dpv_test2.e
TWO=$?
[ $ONE != 99 ] || [ $TWO != 99 ] && {
  echo "`date`:  port verify failed on wals1-int" >> $LOG
  echo "" | mailx -s "port verify failed on wals1-int" 9014774388@my2way.com
  exit 2
}
echo "`date`:  dpv2s tested successfully" >> $LOG
echo "`date`:  dpv2s restarted. PID: `cat /tmp/dpv.pid`. Time: `ps -ef | grep dpv2s | grep -v grep | awk '{print $5}'`" >> $LOG
echo "" | mailx -s "wal1-int dpv data updated at `date`" 9014774388@my2way.com

### create tag file for prod servers
touch /home/amsauto/data/verified.tag

exit 0
